### ISSUE TITLE
Incorrect WIF Private Keys (Uncompressed and Compressed)

### ISSUE THREAD

**Issue by boodooboo** [Mizogg/Python-WebServer#1]
Hello.
Thanks for the script.
But there is a problem. WIF private keys are generated incorrectly.
Example: HEX 000...01
Correct:
KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn and 
5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAnchuDf

Your script generates:
KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sTVMPB5 and
5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAiK7XiF

Thanks.

**Comment by Mizogg** [comment]
Hi, 
Very Strange I have tested and dont get the same results as you. When I test I get correct WIFS
Example: HEX 000...01
Correct:
KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn and
5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAnchuDf

```
Private Key Hex                                                          Uncompressed Address                Compressed Address                       SegWit 3 Address                  bech32 bc1 Address                           ETH Address                           WIF Private Key Uncompressed                            WIF Private Key Compressed
0000000000000000000000000000000000000000000000000000000000000001  [1EHNa6Q4Jz2uvNExL497mE43ikXhwF6kZm] [1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH]      [3JvL6Ymt8MVWiCNHC7oWU6nLeHNJKLZGLN]   [bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4]          [0x7e5f4552091a69125d5dfcb7b8c2659029395bdf]          5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAnchuDf  KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn
```
![image](https://user-images.githubusercontent.com/88630056/166555700-584f4291-37d8-402d-af31-ae529d0ecd4b.png)

**Comment by boodooboo** [comment]
Lol.

![lol](https://user-images.githubusercontent.com/165537/166561773-f0308b82-5cac-4d51-a25e-0b82f58bb862.png)
