### ISSUE TITLE
Contacting you

### ISSUE THREAD

**Issue by Adrianoross** [Mizogg/Python-WebServer#3]
I sent some mails.
Hopefully you can make the time to check them out.
Thank you

**Comment by Mizogg** [comment]
Good Afternoon Adrianonross,
I have made in my https://github.com/Mizogg/Mizogg-Tools option 23 addresses from file to public key if known. Or just go there yourself like this https://blockchain.info/q/pubkeyaddr/1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH 

I hope that helps

Thanks Mizogg
