### ISSUE TITLE
Bloomfilter does not work for ETH addresses.

### ISSUE THREAD

**Issue by enfarktus** [Mizogg/Python-WebServer#4]
First of all, thanks for all your shares. Bloomfilter does not work for ETH addresses. I add the eth addresses, whose private key I know, to the bf file, but no match is found. The same situation does not work in different scripts.

**Comment by Mizogg** [comment]
We have had problems with bloom filter for ETH . If you remove the 0x from your addresses and try again hopefully this will work for you.
