### ISSUE TITLE
Found Key  66Bit

### ISSUE THREAD

**Issue by NsAaa** [Mizogg/Python-WebServer#5]
Hi

I was testing using your server today, sometime between 2pm and 11pm GMT+1.
I found 1 key in the 66Bit range.
Current random range = 288230376151711745 - 576460752303423489

Could you check your found .txt and see if it is they key for the 66Bit BTC puzzle 

If so I'm happy to work out a split!

**Comment by Betovisck103** [comment]
I found these addresses, but the page provided does not match, what could have happened?
Was it the number of operating windows?
What is the maximum number of tabs I can leave open?


ETH Address: 0x252dae0a4b9d9b80f504f6418acd2d364c0c59cd Found on Page# 1477593352933727610083810943875614163 
ETH Address: 0x252dae0a4b9d9b80f504f6418acd2d364c0c59cd Found on Page# 1477593352933727610083810943875614163

**Comment by Mizogg** [comment]
I wish that was true but for now I don't  have that key saved in text file.  please see this comment https://github.com/Mizogg/Python-WebServer/issues/6 

Please keep trying i'm sure someone will find it one day
