### ISSUE TITLE
found

### ISSUE THREAD

**Issue by Betovisck103** [Mizogg/Python-WebServer#6]
I found these addresses, but the page provided does not match, what could have happened?
Was it the number of operating windows?
What is the maximum number of tabs I can leave open?

ETH Address: 0x252dae0a4b9d9b80f504f6418acd2d364c0c59cd Found on Page# 1477593352933727610083810943875614163
ETH Address: 0x252dae0a4b9d9b80f504f6418acd2d364c0c59cd Found on Page# 1477593352933727610083810943875614163

**Comment by Mizogg** [comment]
Python-WebServer is great if you are the only one using it. If I am scanning and another user starts scanning from another web browser and they go to a low page which already how found addresses like page 1. This will report as a found for all users that are scanning at that moment in time. My test site you have been using is just for testing it Python-WebServer out. If you want better performance and the results to be saved to your device when found then you should download and run locally from your device.
